# syntax=docker/dockerfile:1.4

# Imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo requirements.txt al contenedor
COPY requirements.txt .

# Instalar las dependencias del archivo requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todos los archivos del proyecto al contenedor
COPY . .

# Exponer el puerto 5000 (el puerto donde Flask escuchará)
EXPOSE 5000

# Comando para ejecutar el servidor Flask
CMD ["python", "aquasense.py"]
